development:
  adapter: postgresql
  encoding: utf8
  database: todo_from_seven_habits_development
  pool: 5

test:
  adapter: postgresql
  encoding: utf8
  reconnect: false
  database: todo_from_seven_habits_test
  pool: 5

production:
  adapter: postgresql
  encoding: utf8
  database: todo_from_seven_habits
  pool: 5